# head
menu:
  目录: /archives
  # sitemap: /sitemap.xml
  # other menus

rss: /atom.xml
favicon: /favicon.png

date_format: 'MMMM D, YYYY'

google_verification: false  # your token
google_analytics: false   # your id

disqus_shortname: false   # your disqus name

start_year: 2016

reward_images: 
- type: '微信'
  url: '/img/wechat.png'
# - type: '支付宝' 
#   url: '/img/wechat.png'
